apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: game-server-node-connector-clusterrole
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch